name: CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1

      - name: Test
        run: make test

      - name: Build
        run: make build

      - name: E2E Test
        run: make e2e

      - name: Uploads logs if failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: extauthz-e2e-logs
          path: extauthz/e2e/logs

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: extauthz
          platforms: linux/amd64,linux/arm64
          push: false
          tags: openfga/openfga-envoy:dev
