name: Release

on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".github/workflows/release.yaml"

  workflow_dispatch:

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v4

      - name: Checkout
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
  
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1

      - name: Build
        env:
          BUILD_OS: ${{ matrix.os }}
          BUILD_ARCH: ${{ matrix.arch }}
        run: make build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}

      - name: Build and push
        id: push
        uses: docker/build-push-action@v5
        with:
          context: extauthz
          platforms: ${{ matrix.os }}/${{ matrix.arch }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Write summary
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "The image is available:" >> $GITHUB_STEP_SUMMARY
          echo "<pre>docker pull --platform=${{ matrix.os }}/${{ matrix.arch }} ${{ steps.meta.outputs.tags }}@${{ steps.push.outputs.digest }}</pre>" >> $GITHUB_STEP_SUMMARY
